Refactor Authentication Pages and Error Handling
willsf2021/login-register-bible-s-game pull request #2
Opened 2024-10-28 01:06 UTC by willsf2021

This pull request introduces several improvements to the LoginPage and RegisterPage components:

- Simplified the structure of the LoginPage and RegisterPage by reducing the number of exported styled-components and utilizing more JSX tags.
- Moved the isWhatsapp toggle function inline for better readability.
- Removed custom error handling for specific cases (incorrect credentials, existing username, and email) and now displays raw backend error messages directly on the frontend.
- Replaced hard-coded color values with variables from theme.js for improved color management and consistency across the project.

2024-10-28 22:35 UTC, filiperochalopes commented
- [ ] converter rotas para o português
- [ ] criação de versão desktop das páginas com base em figma, para isso é interessante a criação de um componente PageLayout, que sempre fica como pai das páginas organizando a estrutura macro delas
- [ ] a versão mobile deve ocupar sempre a horizontal toda, sendo flexível quando ao posicionamento de seus elementos internos

Note que aqui temos uma margem branca na tela
![image](https://github.com/user-attachments/assets/434fef14-355d-4885-8f68-d732a13c130e)

2024-11-22 09:13 UTC, filiperochalopes commented
![image](https://github.com/user-attachments/assets/aa977c96-3ff2-406d-94c8-6df2bd46c10a)

Telas verticais ainda temos o layout desajustado!

2024-11-22 09:17 UTC, filiperochalopes commented
![image](https://github.com/user-attachments/assets/7f348199-9b55-4c6d-8d57-20739a09120f)

O exemplo mostrado no placeholder está errado, só precisa de DDD e Número

- [ ] Li e concordo com Termos de Uso não tem o link para os termos de uso

Ao cadastrar um novo usuário não temos nenhuma mensagem que foi cadastrado com sucesso. O usuário deve saber que foi cadastrado, o formulário limpo e ser direcionado para tela de login

2024-11-22 10:23 UTC, filiperochalopes requested changes
Precisamos de alguns ajustes 🚀

2024-11-22 10:23 UTC, filiperochalopes commented on README.md
O README.md deve conter informações da aplicação que forem relevantes, esse é um conteúdo provisório e deve ser editado

2024-11-22 10:23 UTC, filiperochalopes commented on package-lock.json
De preferência vamos utilizar yarn e não npm. https://yarnpkg.com/ Mais rápido, menos erros e mantém a consistência do projeto entre nós dois.

2024-11-22 10:23 UTC, filiperochalopes commented on src/components/Header/styles.js
> +      ${colors.gradient.lighterBlue} 35%,
As informações de temas tem uma forma de ser carregada dentro do styled-components, veja: https://styled-components.com/docs/advanced

2024-11-22 10:23 UTC, filiperochalopes commented on src/components/Input/styles.js
>      color: ${colors.primary.lighterBlue};
O mesmo aqui, tema importado de forma errada. Sempre vejamos a documentação do pacote para criar padrões de implementação

2024-11-22 10:23 UTC, filiperochalopes commented on src/styles.js
> +    background-color: ${colors.primary.backgroundDesktop};
https://styled-components.com/docs/advanced

2024-11-22 10:23 UTC, filiperochalopes commented on src/views/AddQuestions/index.jsx
> +import { GET_TEMAS } from "../../services/api";
Import relativo persistente

2024-11-22 10:23 UTC, filiperochalopes commented on src/views/AddQuestions/styles.js
> +import { colors } from "src/services/theme";
https://styled-components.com/docs/advanced

2024-11-22 10:23 UTC, filiperochalopes commented on src/views/Login/index.jsx
> +import Container, { Form, Button } from "./styles";
Form é um elemento que se repete com as mesmas propriedades? Se sim ele deve ser um componente Wraper, algo como FormContainer dentro da pasta container e não apenas um recurso de estilização dentro de Login, vi que você chama o estilo de Login/styles/Form em Register, isso não é bom!

2024-11-22 10:23 UTC, filiperochalopes commented on src/views/Login/styles.js
> +import { colors } from "src/services/theme";
https://styled-components.com/docs/advanced

2024-11-22 10:23 UTC, filiperochalopes commented on src/views/Register/index.jsx
>  import { Form, Button } from "../Login/styles";
Aqui você está importando estilos de Login para Register? Se é algo que se repete deve ser um componente e não um estilo de uma página! Refatorar `git commit -am "refactor: ..."`

2024-11-22 10:23 UTC, filiperochalopes commented on src/views/Register/index.jsx
>    const [cadastrarUsuario, { loading }] = useMutation(REGISTER_USER);
Devemos ter o feedback de erro e resultado também aqui, caso o resultado positivo emite a mensagem de cadastro com sucesso e redireciona para Login, caso error mostra em seu general, para isso seria bom você começar a interagir com o [useEffect](https://react.dev/reference/react/useEffect), uma das funções mais utilizadas no React

2024-11-22 10:23 UTC, filiperochalopes commented on src/views/Register/index.jsx
>        } catch (err) {
Esse catch se transformará em useEffect para a variável error em `const [cadastrarUsuario, { loading, data, error }] = useMutation(REGISTER_USER);`

2024-11-22 10:23 UTC, filiperochalopes commented on src/views/Register/index.jsx
>              placeholder="telefone (ex: +55 11 99999-9999)"
Placeholder "11 98887 7776"

2024-11-22 10:23 UTC, filiperochalopes commented on src/views/Register/index.jsx
>                Li e concordo com os <a href="#">Termos de Uso</a>
Criar uma issue para que eu possa criar os termos de uso e políticas de privacidade, para vc incluir aqui. Nosso objetivo é deixar a página pronta. Dessa forma não está pronta! Se depende de mim, só falar!

2024-11-22 10:23 UTC, filiperochalopes commented on src/views/Register/index.jsx
> +      <footer>
Esse footer fica se repetindo, então deve ser um componente

2024-12-03 01:15 UTC, filiperochalopes requested changes
Estamos chegando lá, mas tivemos muitos erros repetidos, principalmente nos imports relativos, sugiro cautela na escrita das importações

2024-12-03 01:15 UTC, filiperochalopes commented on src/components/BibleRef/styles.js
> +export default styled.div`
Se o estilo é vazio por que manter o arquivo?

2024-12-03 01:15 UTC, filiperochalopes commented on src/components/BibleRef/index.jsx
> +export const BibleRef = ({ isReferenceComplete, setFieldValue }) => {
Fiquei na dúvida se esse é um componente reutilizável. Estamos em um PR para tratar de login e cadastro e não de cadastro de perguntas, esse é tema para outro PR e deve ser tratado exclusivamente lá, aparentemente você deu um merge, vai ficar muito bagunçada as etapas e não vamos sair do lugar assim.

2024-12-03 01:15 UTC, filiperochalopes commented on src/components/Footer/index.jsx
> +  return <Container>{children}</Container>;
O footer é repetido, por que seu conteúdo é um children, assim o componente fica praticamente inútil e restrito à estilização, bom colocar logo o conteúdo que se repete.

2024-12-03 01:15 UTC, filiperochalopes commented on src/components/Footer/styles.js
> +  p {
Gosto sempre de deixar espaço entre os blocos para organização. no caso:

```css
text-align: center;
padding-bottom: 24px;

p {
```

2024-12-03 01:15 UTC, filiperochalopes commented on src/components/FormContainer/index.jsx
> +  return <Container onSubmit={onSubmit}>{children}</Container>;
Só um conselho para tornar mais semântico e legível seu componente, se ele é um Form, bom chamar de `StyledForm` ou algo do tipo.

2024-12-03 01:15 UTC, filiperochalopes commented on src/components/FormContainer/styles.js
> +  @media (min-width: 768px) {
Separação de blocos com linha para organização, opcional.

2024-12-03 01:15 UTC, filiperochalopes commented on src/components/Header/styles.js
> +        0px 3px 0px ${(props) => props.theme.gradient.lighterBlue}
Em vez de usar o `(props) => props.theme...`podemos utilizar desconstruído para escrever menos `({theme}) => theme.gradient`

2024-12-03 01:15 UTC, filiperochalopes commented on src/services/apiBiblia.js
> +  baseURL: "/api/",
o baseURL não termina com `/` pois toda rota se inicia com a barra. Seria `baseURL: "/api"`tendo em vista que você está fazendo uso do proxy.

2024-12-03 01:15 UTC, filiperochalopes commented on src/views/AddQuestions/index.jsx
> +import { Footer } from "../../components/Footer";
Import relativo

2024-12-03 01:15 UTC, filiperochalopes commented on src/views/Login/index.jsx
> +import { FormContainer } from "../../components/FormContainer";
import relativo

2024-12-03 01:15 UTC, filiperochalopes commented on src/views/Login/index.jsx
> +import { Button } from "../../components/Button";
import relativo

2024-12-03 01:15 UTC, filiperochalopes commented on src/views/Login/index.jsx
> +import { Footer } from "../../components/Footer";
import relativo

2024-12-03 01:15 UTC, filiperochalopes commented on src/views/Login/index.jsx
> +      }).catch((error) => {
esse catch não é necessário se você está fazendo uso do useEffect, precisamos estudar mais o uso do `useEffect`

2024-12-03 01:15 UTC, filiperochalopes commented on src/views/Login/index.jsx
>    }, [data, error]);
Podemos criar dois useEffects, um para o data e outro para o error

2024-12-03 01:15 UTC, filiperochalopes commented on src/views/Login/index.jsx
>          <p>Jogo da Bíblia &copy; 2022</p>
Se é um conteúdo que se repete nos rodapés por que não manter no componente `Footer`?

2024-12-03 01:15 UTC, filiperochalopes commented on src/views/Register/index.jsx
> +import { Button } from "../../components/Button";
import relativo

2024-12-03 01:15 UTC, filiperochalopes commented on src/views/Register/index.jsx
> +import { Footer } from "../../components/Footer";
import relativo

2024-12-03 11:26 UTC, willsf2021 commented on src/components/BibleRef/styles.js
> +export default styled.div`
Ainda não fiz a estilização, foi só para criar o componente, mas vou estilizá-lo.

2025-02-02 11:28 UTC, filiperochalopes approved these changes

2025-02-02 11:28 UTC, filiperochalopes commented on src/App.jsx
> +          future={{ v7_relativeSplatPath: true, v7_startTransition: true }}
Em vez de usar flags da versão futura, por que não utilizar a versão 7 que já está em produção do React Router https://reactrouter.com/7.1.5/home e poupar esse trabalho?

2025-02-02 13:08 UTC, merged